### ISSUE TITLE
Lack of releases

### ISSUE THREAD

**Issue by grepwood** [CheezeCake/ps3linux-patches#1]
Hello,

I wish to package the kernel sources for Gentoo with these patches, but it's unclear which version of 5.3 is being tracked. That way a particular version of sys-kernel/gentoo-sources could be finely matched against these patches.

Any chance there would be releases?

**Comment by CheezeCake** [comment]
Hi,

Currently, the patches apply cleanly to the latest upstream kernel (5.6.15). They should also apply to any version all the way back to 5.3, since there hasn't been any significant change since then.

But that's a good idea, I'll make a release every time the patches need to be rebased to a new kernel version.

Thanks.

**Comment by grepwood** [comment]
>Currently, the patches apply cleanly to the latest upstream kernel (5.6.15). They should also apply to any version all the way back to 5.3

Wow. That's honestly amazing! You know, when glevand used to maintain ps3linux-patches, there was always something changing from branch to branch and that's stuff from 2.6.32 all the way up to 3.15.

I also applied your patches in an ebuild planned for release soon. They're applying just great!

**Comment by CheezeCake** [comment]
I made a release for the 5.7 changes.
